---
new_page_extension: html
auto_deploy: true
admin_path: admin
webhook_url: https://api.stackbit.com/project/5d44d1798bf0300012f19fdb/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Global Site Config
  templates:
  - config
- type: document
  path: _data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: _data/author.json
  label: Author
  templates:
  - author
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: document
  path: contact.md
  label: Contact
  templates:
  - contact
- type: directory
  path: ''
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{_posts/**,README.md,LICENSE.md,index.md,contact.md}"
  templates:
  - hsyh
  - page
- type: jekyll-posts
  label: Post
  create: all
  templates:
  - post
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: _site
  mount_path: _site
